### ISSUE TITLE
Le tri sur colonne ne marche pas après un badgeage

### ISSUE THREAD

**Issue by vinriviere** [EsupPortail/esup-emargement#12]
Je vais sur l'écran Surveillant > Emargement.
Je sélectionne une session.
On peut cliquer sur les en-têtes de colonnes pour trier la liste : c'est ce qu'il faut.

Ensuite : 
- Je scanne une carte, et je confirme.
- L'écran se rafraîchit automatiquement.
- Mais si maintenant je clique sur un en-tête de colonne pour trier, cela provoque un bug. La page s'affiche mal : seule la liste apparaît sur fond blanc. Si je regarde le source HTML, on voit que les données commencent par un \<div>. On a perdu une partie de la page.

Il faut que le clic sur les colonnes soit toujours possible pour trier, même après un rafraîchissement automatique.

**Comment by jptran** [comment]
Corrigé depuis le commit du 21/03/24
