### ISSUE TITLE
Emargement : Tri par personne ne marche pas

### ISSUE THREAD

**Issue by vinriviere** [EsupPortail/esup-emargement#13]
Page Surveillant > Emargement.
Le tri sur "Personne" ne marche pas. Quand on clique sur l'en-tête de colonne, il semble que le tri s'effectue sur eppn. Alors qu'il devrait s'effectuer sur le nom affiché.

Ce problème est similaire à l'Issue #4 concernant les Lieux.

**Comment by vinriviere** [comment]
Je vois une piste [ici](https://stackoverflow.com/questions/37139985/spring-data-jpa-is-it-possible-to-sort-on-a-calculated-property). A ce que je comprends, Spring Data JPA ne peut trier que sur des champs de base de données. Comme les noms et prénoms sont récupérés dynamiquement depuis LDAP, ces champs ne sont pas stockés en base de données dans la table `person`. Et donc on ne peut pas trier sur le nom affiché. C'est dommage, il faudrait trouver une solution pour que ce soit possible.

Par ailleurs, quand il y a beaucoup de personnes sur une page, l'affichage est lent à cause des nombreuses requêtes LDAP pour récupérer les noms et prénoms. On pourrait stocker une copie des nom et prénom dans la table `person`, ça résoudrait les deux problèmes.

**Comment by jptran** [comment]
Corrigé depuis le commit du 21/03/24
