### ISSUE TITLE
Rafraîchir la page Surveillant après le badgeage d'un inconnu

### ISSUE THREAD

**Issue by vinriviere** [EsupPortail/esup-emargement#14]
Page Surveillant, session non libre :
Il serait utile de rafraîchir la page après avoir scanné la carte d'une personne inconnue de la session.
Autrement dit, il faudrait toujours rafraîchir la page après un badgeage : que la personne soit connue ou non.

Ainsi, tout surveillant pourra suivre l'évolution des badgeages sans jamais avoir à rafraîchir la page avec F5.

**Comment by jptran** [comment]
Correction dans un des commits du 13/11/2023

**Comment by vinriviere** [comment]
Merci Jean-Pierre. Je viens de tester en pré-production, ça marche.
