### ISSUE TITLE
Session libre : badgé 2 fois

### ISSUE THREAD

**Issue by vinriviere** [EsupPortail/esup-emargement#15]
Session libre : 
- Je badge 1 seule fois
- Mais sur l'écran du surveillant, j'obtiens immédiatement une alerte : "... a badgé(e) 2 fois"
- Et sur l'écran Gestionnaire > Sessions > Inscrits, je vois également que le champ "Nb badgeage" est à 2.

Ce n'est pas normal : chaque badgeage ne doit être comptabilisé qu'une fois.
A cause de ce bug, l'alerte badgeage max n'est plus utilisable sur les sessions libres, étant donné que l'alerte se déclenche à tous les coups.

**Comment by vinriviere** [comment]
Pour info, j'ai testé à la fois avec esup-nfc-tag-desktop et esup-nfc-tag-droid : les deux provoquent le problème.

**Comment by jptran** [comment]
Correction  : commit du 23 janvier 2023

**Comment by vinriviere** [comment]
Merci, ça marche 👍
