### ISSUE TITLE
Problème de récupération des Composantes ADE Campus

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-emargement#16]
Bonjour
Lors de la récupération des Composantes (branches "trainee" dans ADE), je constate que la constitution de la Map se fait sur le code et non l'id comme c'est fait pour les salles.
Le problème est qu'on n'a pas forcément de code sur nos dossiers et de fait, on ne remonte pas tous les éléments.
Merci de ne pas utiliser le champs Code pour cette Map

**Comment by jptran** [comment]
Bonjour,
changement effectué dans le commit du 08/11/23 concernant la refonte de l'interface Adecampus.
