### ISSUE TITLE
Longueur du champs "key" de la table type_session

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-emargement#17]
Bonjour,
Lors de l'ajout de session via la récupération de cours sur la partie ADECampus, nous avons constaté que le type de l'activité servait pour la correspondance du type de session.
Le problème est que nos types ne sont pas de code mais du texte et dépasse donc la limite de 5 caractères du champs "key".
Nous avons donc l'erreur suivante : 
ERROR o.h.e.jdbc.spi.SqlExceptionHelper.logExceptions - Batch entry 0 insert into type_session (add_by_admin, comment, context_id, date_modification, key, libelle, id) values ('TRUE', 'Ajouté d''Ade Campus', 1, '2023-10-17 11:11:05.565+02', 'Cours de langue', 'Cours de langue', 195) was aborted: ERREUR: valeur trop longue pour le type character varying(5)  Call getNextException to see other errors in the batch.
Merci d'agrandir la taille de ce champs.

**Comment by jptran** [comment]
Bonjour,
changement effectué dans ce commit : https://github.com/EsupPortail/esup-emargement/commit/ef6386d0057a3792de74c25678691fb88ffea855
