### ISSUE TITLE
L'heure affichée dans l'interface Surveillant n'est pas bonne

### ISSUE THREAD

**Issue by vinriviere** [EsupPortail/esup-emargement#25]
J'ai récemment mis à jour Esup-emargement avec la version actuelle de GitHub (mon ancienne version datait de l'an dernier). Dans l'interface surveillant, il y a un problème sur l'affichage de l'heure d'émargement. Le format de date est sur 12 heures au lieu de 24, et elle a 1 heure de retard. Tout porte à croire que c'est l'heure UTC qui s'affiche, ce n'est pas bon. Auparavant ça fonctionnait correctement.

Heure réelle :
![image](https://github.com/user-attachments/assets/b45cab1f-56e2-4525-8e89-54fdc410ef7e)

Base de données : OK
![image](https://github.com/user-attachments/assets/3b198bdd-304d-41b7-b5d6-b446cd846960)

Heure affichée dans l'interface Surveillant: KO
![image](https://github.com/user-attachments/assets/426d4d59-0303-4662-8b20-eecfb5c755c8)

**Comment by jptran** [comment]
Je viens de pousser la correction. Merci Vincent.

**Comment by vinriviere** [comment]
Merci @jptran, ça marche.

![image](https://github.com/user-attachments/assets/70f7b9bb-6bf2-4541-b014-2793dce89975)
