### ISSUE TITLE
Affichage de la photo lors de la confirmation de l'émargement

### ISSUE THREAD

**Issue by bquiller** [EsupPortail/esup-emargement#6]
Bonjour,

Il serait bien d'afficher la photo lors du message "Confirmer le badgeage de Prénom Nom" : cela permettrait de valider l'identité de l'étudiant.

Merci,
Cordialement.

**Comment by vinriviere** [comment]
J'allais faire la même demande ! Je me joins à vous. Confirmer un badgeage sans photo n'a pas de sens.

**Comment by bquiller** [comment]
Cela est finalement intégré : dans la configuration, il faut mettre ENABLE_PHOTO_ESUPNFCTAG à true.
